# Generated by Django 5.0.3 on 2024-04-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_user_id_remove_vote_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_ciphertext',
            field=models.BinaryField(max_length=3000),
        ),
    ]
