# Generated by Django 5.0.3 on 2024-04-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_vote_vote_ciphertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_ciphertext',
            field=models.BinaryField(max_length=4096),
        ),
    ]
