# Generated by Django 5.0.3 on 2024-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_vote_vote_ciphertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_ciphertext',
            field=models.CharField(max_length=1024),
        ),
    ]
